import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box } from "@chakra-ui/layout"
import { Header } from "../components/header"
import { TopWorks } from "../components/temp"
import { Footer } from "../components/footer"
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Page2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Header/>
      </Box>
      <Box>
        <TopWorks/>
      </Box>
      <Box>
        <Footer/>
        </Box>
    </div>
  )
}
